### ISSUE TITLE
Bindings sometimes switch back to default + Pass turn has a buggy behaviour when used for long

### ISSUE THREAD

**Issue by mariusehr1** [Yokani/DofusHeroes#2]
Hi,

First of, nice work and very good concept, though it could be improved a bit.

I used your program for a little while with 8 accounts and I noticed some bugs :  

It can happen that one of the bound keys is just not responding, looking at the GUI I noticed that they were back to "default" and forced me to rebind the key, which is not too annoying but could probably be fixed.

The second issue I'm having is a little more bothering me : the pass turn feature is not working as intended : I bound the key within Dofus to use INSERT , when passing my turn, the key is detected and it works ingame.

The problem appears after some time using the script : even though INSERT is bound in the UI and ingame, the pass turn feature will switch windows but it will not pass the turn when its written in both the game and the GUI conf.

My feeling is that , looking at your code, I kinda has to be AHK-related but I wonder if you have any hints on this.

Thanks a lot.
Marius

**Comment by Yokani** [comment]
Hey,

first of all thanks for using the tool and giving feedback!
I'm currently working on another major feature, which should be ready soon.
Regarding your issues:

a) configurations returning to default
That happens sometimes with special keys, for me it's with circumflex. I think the problem lies with reloading the settings when reopening the program. I'll look into it further.

b) pass command not dropped off properly
This shouldn't happen. Could it be that your chat window was activated? If so, it probably catched your end-turn command.
I'll try to think of a way to make it more reliable.

**Comment by mariusehr1** [comment]
Hi,

Indeed, I had the issue with both circumflex and exclamation mark (on a French keyboard though). It has to do with the program being put on foreground or reduced. But it would be interesting to have it fixed.

For the second point I didn't have a special explanation for it but I do have a workaround : if you bind you end of turn and your change character bindings to the same key, it effectively changes window focus and pass turn. Again, it works for now but it could be a bit more reliable.

Closing the issue for now as its just some improvements for later.
Thanks
